CREATE TABLE [dbo].[CommonDatas] (
    [Id]                        INT              IDENTITY (1, 1) NOT NULL,
    [Status]                    INT              NOT NULL,
    [PayoutDate]                DATETIME2 (7)    NULL,
    [DonationDate]              DATETIME2 (7)    NOT NULL,
    [DonorFirstName]            NVARCHAR (MAX)   NULL,
    [DonorLastName]             NVARCHAR (MAX)   NULL,
    [DonorEmail]                NVARCHAR (MAX)   NULL,
    [ProgramName]               NVARCHAR (MAX)   NULL,
    [ReferenceInformation]      NVARCHAR (MAX)   NULL,
    [CurrencyCode]              NVARCHAR (MAX)   NULL,
    [GrossAmount]               DECIMAL (18, 2)  NULL,
    [TotalFees]                 DECIMAL (18, 2)  NULL,
    [NetAmount]                 DECIMAL (18, 2)  NULL,
    [TransactionID]             NVARCHAR (MAX)   NULL,
    [Company]                   NVARCHAR (MAX)   NULL,
    [Project]                   NVARCHAR (MAX)   NULL,
    [Address]                   NVARCHAR (MAX)   NULL,
    [City]                      NVARCHAR (MAX)   NULL,
    [State]                     NVARCHAR (MAX)   NULL,
    [PostalCode]                NVARCHAR (MAX)   NULL,
    [Activity]                  NVARCHAR (MAX)   NULL,
    [DonationFrequency]         NVARCHAR (MAX)   NULL,
    [ProjectRemoteID]           NVARCHAR (MAX)   NULL,
    [CauseSupportFee]           DECIMAL (18, 2)  NULL,
    [Description]               NVARCHAR (MAX)   NULL,
    [Comment]                   NVARCHAR (MAX)   NULL,
    [Source]                    NVARCHAR (MAX)   NULL,
    [BankName]                  NVARCHAR (MAX)   NULL,
    [ShippingandHandlingAmount] DECIMAL (18, 2)  NOT NULL,
    [BankAccount]               NVARCHAR (MAX)   NULL,
    [InvoiceID]                 NVARCHAR (MAX)   NULL,
    [SalesTax]                  DECIMAL (18, 2)  NOT NULL,
    [FileName]                  NVARCHAR (MAX)   NULL,
    [FileLocation]              NVARCHAR (MAX)   NULL,
    [ReferenceNote]             NVARCHAR (MAX)   NULL,
    [DBProjectId]               UNIQUEIDENTIFIER NULL,
    [ProjectName]               NVARCHAR (MAX)   NULL,
    [DBDonorId]                 UNIQUEIDENTIFIER NULL,
    [DonorName]                 NVARCHAR (MAX)   NULL,
    [DBBeneficiaryId]           UNIQUEIDENTIFIER NULL,
    [BeneficiaryName]           NVARCHAR (MAX)   NULL,
    [DBTransactionId]           UNIQUEIDENTIFIER NULL,
    [CurrencyRate]              DECIMAL (18, 2)  CONSTRAINT [DF__CommonDat__Curre__6FB49575] DEFAULT ((0.0)) NOT NULL,
    [CurrencyType]              NVARCHAR (MAX)   NULL,
    [DonorCode]                 NVARCHAR (MAX)   NULL,
    [CreateDate]                DATETIME         NULL,
    [ConvertedAmount]           DECIMAL (18, 2)  CONSTRAINT [DF_CommonDatas_ConvertedAmount] DEFAULT ((0)) NULL,
    [IsDebitAmount]             BIT              CONSTRAINT [DF_CommonDatas_IsDebitAmount] DEFAULT ((0)) NULL,
    [IsSendToAllocation]        BIT              CONSTRAINT [DF_CommonDatas_IsSendToAllocation] DEFAULT ((0)) NULL,
    [Note]                      NVARCHAR (MAX)   NULL,
    [DonorMatchedNumber]        INT              CONSTRAINT [DF_CommonDatas_DonorMatchedNumber] DEFAULT ((0)) NULL,
    [DonationAllocationId]      UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_CommonDatas] PRIMARY KEY CLUSTERED ([Id] ASC)
);

